export const browserCoreExamples = [
  "opennexus browser status",
  "opennexus browser start",
  "opennexus browser stop",
  "opennexus browser tabs",
  "opennexus browser open https://example.com",
  "opennexus browser focus abcd1234",
  "opennexus browser close abcd1234",
  "opennexus browser screenshot",
  "opennexus browser screenshot --full-page",
  "opennexus browser screenshot --ref 12",
  "opennexus browser snapshot",
  "opennexus browser snapshot --format aria --limit 200",
  "opennexus browser snapshot --efficient",
  "opennexus browser snapshot --labels",
];

export const browserActionExamples = [
  "opennexus browser navigate https://example.com",
  "opennexus browser resize 1280 720",
  "opennexus browser click 12 --double",
  'opennexus browser type 23 "hello" --submit',
  "opennexus browser press Enter",
  "opennexus browser hover 44",
  "opennexus browser drag 10 11",
  "opennexus browser select 9 OptionA OptionB",
  "opennexus browser upload /tmp/opennexus/uploads/file.pdf",
  'opennexus browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "opennexus browser dialog --accept",
  'opennexus browser wait --text "Done"',
  "opennexus browser evaluate --fn '(el) => el.textContent' --ref 7",
  "opennexus browser console --level error",
  "opennexus browser pdf",
];
